# Generated by Django 4.2.9 on 2024-01-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0003_content_marked_alter_content_bits'),
    ]

    operations = [
        migrations.AddField(
            model_name='bits',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
