# Generated by Django 4.2.9 on 2024-01-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0005_remove_bits_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='bits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='bits.bits'),
        ),
    ]
