# Generated by Django 4.2.9 on 2024-01-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0007_alter_content_bits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bits',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
